import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth/next";
import { authOptions } from "/pages/api/auth/[...nextauth]";
import LogOutBtn from "./LogOutBtn";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);
    let res = cookies().get("mode");
    console.log(res.value);

    return (
        <html lang="en">
            <body className={`${res?.value == "dark" ? "dark-mode" : ""} ${geistSans.variable} ${geistMono.variable}`}>
                <div className="navbar">
                    <Link href="/" className="logo">
                        Appleforum
                    </Link>
                    <Link href="/list">List</Link>
                    <Link href="/write">Write</Link>

                    {session ? (
                        <span>
                            {session.user.name} <LogOutBtn />
                        </span>
                    ) : (
                        <LoginBtn />
                    )}

                    <DarkMode />
                </div>
                {children}
            </body>
        </html>
    );
}
